---
version: 2.1

commands:
  setup_project:
    description: "Setup the machine, clone the repo, checkout the submodules."
    steps:
      - checkout
      - add_ssh_keys
      - run: apt-get update && apt-get install -y z3 git ssh
      - run: git submodule sync
      - run: git submodule update --init

jobs:
  stack_build:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - setup_project
      - restore_cache:
          keys:
            - stack-{{ checksum "stack.yaml" }}
      - run:
          name: Dependencies
          command: |
            stack setup
            # rm -fr $(stack path --dist-dir) $(stack path --local-install-root)
            stack build liquidhaskell --only-dependencies --test --no-run-tests
      - save_cache:
          key: stack-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work

  stack_test:
    docker:
      - image: fpco/stack-build:lts
    steps:
      - restore_cache:
          keys:
            - stack-{{ checksum "stack.yaml" }}
      - run:
          name: Test
          command: |
            stack clean
            mkdir -p /tmp/junit/stack
            stack test -j1 liquidhaskell:test --flag liquidhaskell:include --flag liquidhaskell:devel --test-arguments="-t 1200s --xml=/tmp/junit/stack/main-test-results.xml": #--liquid-opts='--cores=1'":
            stack test -j1 liquidhaskell:liquidhaskell-parser --test-arguments="--xml=/tmp/junit/stack/parser-test-results.xml":
            stack sdist
            # stack haddock liquidhaskell --flag liquidhaskell:-devel --no-haddock-deps --haddock-arguments="--no-print-missing-docs --odir=$CIRCLE_ARTIFACTS"
            stack haddock liquidhaskell  --no-haddock-deps --haddock-arguments="--no-print-missing-docs"
      - store_test_results:
          path: /tmp/junit/stack
      - store_artifacts:
          path: tests/logs/cur
      - run:
          name: Dist
          command: stack sdist

  cabal_build:
    docker:
      - image: haskell:8.6.5
    steps:
      - setup_project
      - restore_cache:
          keys:
            - cabal-{{ checksum "liquidhaskell.cabal" }}
      - run:
          name: Dependencies
          command: |
            cabal new-build all
      - save_cache:
          key: cabal-{{ checksum "liquidhaskell.cabal" }}
          paths:
            - ~/.cabal/store
            - ./dist-newstyle

  cabal_test:
    docker:
      - image: haskell:8.6.5
    steps:
      - restore_cache:
          keys:
            - cabal-{{ checksum "liquidhaskell.cabal" }}
      - run:
          name: Test
          command: |
            cabal new-clean
            mkdir -p /tmp/junit/cabal
            cabal new-test 
            cabal new-test -j1 liquidhaskell:test --flag include --flag devel --test-options="-t 1200s --xml=/tmp/junit/cabal/main-test-results.xml":
            cabal new-test -j1 liquidhaskell:liquidhaskell-parser --test-options="--xml=/tmp/junit/cabal/parser-test-results.xml":
      - store_test_results:
          path: /tmp/junit/cabal
      - store_artifacts:
          path: tests/logs/cur

workflows:
  version: 2
  build_stack_and_cabal:
    jobs:
      - stack_build
      - cabal_build
      - stack_test:
          requires:
              - stack_build
      - cabal_test:
          requires:
              - cabal_build
              - stack_test
