site_name: LiquidHaskell

nav:
    - Home: index.md
    - Install: plugin.md
    - Play: "https://liquid-demo.programming.systems/index.html"
    - Learn:
      - Blog: "https://ucsd-progsys.github.io/liquidhaskell-blog/"
      - Options: options.md
      - Specifications: specifications.md
    - "Get Involved": contributing.md
    - "<i class='fa fa-github'></i>&nbsp;Github": "https://github.com/ucsd-progsys/liquidhaskell"


theme: spacelab

markdown_extensions:
    - toc:
        permalink: true
